# Read about `build.yaml` at https://pub.dev/packages/build_config
builders:

  map_map_generator:
    import: "package:map_mapper_generator/map_mapper_generator.dart"
    builder_factories: ["mapMapBuilder"]
    build_extensions: {".dart": ["map.g.part"]}
    auto_apply: dependents
    build_to: cache
    applies_builders: ["source_gen|combining_builder"]

