name: squarealfa_entity_annotations
description: Annotations and classes to drive code generation for validation and entity life cycle.
homepage: https://github.com/squarealfa/dart_framework/tree/main/entity/entity_annotations
repository: https://github.com/squarealfa/dart_framework
version: 1.1.2

environment:
  sdk: ">=2.12.0 <3.0.0"

dev_dependencies:
  pedantic: ^1.9.0
  
dependencies:
  decimal: ^1.0.0
